In [ ]:
import torch
print(torch.__version__)

2.6.0+cu124


Creating a Tensor

In [ ]:
#using empty
a = torch.empty(2,3)

In [ ]:
# check type
type(a)

torch.Tensor

In [ ]:
#using zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
#using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.9239, 0.3527, 0.2848],
        [0.4451, 0.2779, 0.0112]])

In [ ]:
#manual seed (to have reproducibility in case of random tensor formation)
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
torch.manual_seed(42)
torch.rand(2,3)

tensor([[0.8823, 0.9150, 0.3829],
        [0.9593, 0.3904, 0.6009]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
print("using arange ->", torch.arange(0,10,2))

# using linspace
print("using linspace ->", torch.linspace(0,10, steps=5))

# using eye (identity matrix)
print("using eye ->", torch.eye(5))

# using full (every element of the tensor becomes 5)
print("using full ->", torch.full((2,3), 5))


using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5]])


Tensor Shapes

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])

In [ ]:
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[3347419672810094592, 7310593858020254331, 3616445622929465956],
        [6066964618762267957, 3473183746339517488, 6500163446996416046]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype = torch.float32)

tensor([[0.2566, 0.7936, 0.9408],
        [0.1332, 0.9346, 0.5936]])

Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype = torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype = torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

Mathematical Operations

1. Scalar Operations

In [ ]:
x = torch.rand(2,3)

In [ ]:
x

tensor([[0.8694, 0.5677, 0.7411],
        [0.4294, 0.8854, 0.5739]])

In [ ]:
# addition
x + 2
# subtraction
x - 2
# multiplication
x * 3
# division
x / 3
# int division
(x * 100)//3
# mod
((x * 100)//3)%2
# power
x ** 2

tensor([[0.7559, 0.3223, 0.5492],
        [0.1844, 0.7840, 0.3294]])

2. Element Wise Operation

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.2666, 0.6274, 0.2696],
        [0.4414, 0.2969, 0.8317]])
tensor([[0.1053, 0.2695, 0.3588],
        [0.1994, 0.5472, 0.0062]])


In [ ]:
# add
a+b
# subtract
a-b
# multiply
a*b
# divide
a/b
# power
a**b
# mod
a%b

tensor([[5.5950e-02, 8.8459e-02, 2.6963e-01],
        [4.2636e-02, 2.9692e-01, 2.6345e-05]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

In [ ]:
# abs
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
# round
torch.round(torch.tensor([1.2,1.5,1.8]))

tensor([1., 2., 2.])

In [ ]:
# ceil
torch.ceil(torch.tensor([1.2,1.5,1.8]))

tensor([2., 2., 2.])

In [ ]:
# floor
torch.floor(torch.tensor([1.2,1.5,1.8]))

tensor([1., 1., 1.])

In [ ]:
# clamp
torch.clamp(torch.tensor([1,2,3,4,5]), min = 2, max = 4)

tensor([2, 2, 3, 4, 4])

3. Reduction Operation

In [ ]:
e = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)

In [ ]:
e

tensor([[9., 6., 2.],
        [0., 6., 2.]])

In [ ]:
# sum
torch.sum(e)

tensor(25.)

In [ ]:
# mean
torch.mean(e)

tensor(4.1667)

4. Matrix Operations

In [ ]:
f = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
g = torch.randint(size = (3,2), low = 0, high = 10, dtype = torch.float32)

In [ ]:
# Matrix Multiplication
torch.matmul(f,g)

tensor([[ 21., 193.],
        [  9.,  84.]])

In [ ]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])


In [ ]:
# dot product
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
torch.transpose(f, 0, 1)

tensor([[7., 3.],
        [9., 3.],
        [7., 4.]])

In [ ]:
h = torch.randint(size = (3,3), low = 0, high = 10, dtype = torch.float32)
h

tensor([[1., 7., 9.],
        [4., 3., 8.],
        [9., 3., 7.]])

In [ ]:
# determinant
torch.det(h)

tensor(170.)

In [ ]:
# inverse
torch.inverse(h)

tensor([[-0.0176, -0.1294,  0.1706],
        [ 0.2588, -0.4353,  0.1647],
        [-0.0882,  0.3529, -0.1471]])

5. Comparision Operations

In [ ]:
i = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
j = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)

print(i)
print(j)

tensor([[8., 1., 4.],
        [1., 6., 3.]])
tensor([[2., 0., 9.],
        [8., 5., 3.]])


In [ ]:
# greater than
i>j
# less than

# equal to

tensor([[ True,  True, False],
        [False,  True, False]])

6. Special Functions

In [ ]:
k = torch.randint(size = (2,3), low = 0, high = 10, dtype = torch.float32)
k

tensor([[7., 7., 5.],
        [9., 1., 5.]])

In [ ]:
#log
torch.log(k)

tensor([[1.9459, 1.9459, 1.6094],
        [2.1972, 0.0000, 1.6094]])

In [ ]:
#exp
torch.exp(k)

tensor([[1.0966e+03, 1.0966e+03, 1.4841e+02],
        [8.1031e+03, 2.7183e+00, 1.4841e+02]])

In [ ]:
torch.sqrt(k)

tensor([[2.6458, 2.6458, 2.2361],
        [3.0000, 1.0000, 2.2361]])

In [ ]:
torch.sigmoid(k)

tensor([[0.9991, 0.9991, 0.9933],
        [0.9999, 0.7311, 0.9933]])

In [ ]:
torch.softmax(k, dim = 0)

tensor([[0.1192, 0.9975, 0.5000],
        [0.8808, 0.0025, 0.5000]])

Inplace Operation

In [ ]:
m = torch.rand(2,3)
n = torch.rand(2,3)
print(m)
print(n)

tensor([[0.9578, 0.3313, 0.3227],
        [0.0162, 0.2137, 0.6249]])
tensor([[0.4340, 0.1371, 0.5117],
        [0.1585, 0.0758, 0.2247]])


In [ ]:
m.add_(n)

tensor([[1.3918, 0.4683, 0.8345],
        [0.1747, 0.2895, 0.8496]])

In [ ]:
m

tensor([[1.3918, 0.4683, 0.8345],
        [0.1747, 0.2895, 0.8496]])

In [ ]:
m.relu_() # underscore means inplace operation

tensor([[1.3918, 0.4683, 0.8345],
        [0.1747, 0.2895, 0.8496]])

Copying a Tensor

In [ ]:
a = torch.rand(2,3)
a

tensor([[0.0624, 0.1816, 0.9998],
        [0.5944, 0.6541, 0.0337]])

In [ ]:
b = a

In [ ]:
b

tensor([[0.0624, 0.1816, 0.9998],
        [0.5944, 0.6541, 0.0337]])

In [ ]:
a[0][0] = 0

In [ ]:
a

tensor([[0.0000, 0.1816, 0.9998],
        [0.5944, 0.6541, 0.0337]])

In [ ]:
b

tensor([[0.0000, 0.1816, 0.9998],
        [0.5944, 0.6541, 0.0337]])

In [ ]:
id(a)

137335957151408

In [ ]:
id(b)

137335957151408

In [ ]:
b = a.clone()

In [ ]:
a[0][0] = 10

In [ ]:
a

tensor([[10.0000,  0.1816,  0.9998],
        [ 0.5944,  0.6541,  0.0337]])

In [ ]:
b

tensor([[0.0000, 0.1816, 0.9998],
        [0.5944, 0.6541, 0.0337]])

In [ ]:
id(a)

137335957151408

In [ ]:
id(b)

137335957150352

Tensor Operations on GPU

In [ ]:
torch.cuda.is_available()

False

Reshaping Tensors

In [ ]:
a = torch.rand(4,4)
a

tensor([[0.1716, 0.3336, 0.5782, 0.0600],
        [0.2846, 0.2007, 0.5014, 0.3139],
        [0.4654, 0.1612, 0.1568, 0.2083],
        [0.3289, 0.1054, 0.9192, 0.4008]])

In [ ]:
# reshape
a.reshape(2,2,2,2)

tensor([[[[0.1716, 0.3336],
          [0.5782, 0.0600]],

         [[0.2846, 0.2007],
          [0.5014, 0.3139]]],


        [[[0.4654, 0.1612],
          [0.1568, 0.2083]],

         [[0.3289, 0.1054],
          [0.9192, 0.4008]]]])

In [ ]:
# flatten
a.flatten()

tensor([0.1716, 0.3336, 0.5782, 0.0600, 0.2846, 0.2007, 0.5014, 0.3139, 0.4654,
        0.1612, 0.1568, 0.2083, 0.3289, 0.1054, 0.9192, 0.4008])

In [ ]:
b = torch.rand(2,3,4)
b

tensor([[[0.9762, 0.0405, 0.1854, 0.6252],
         [0.7793, 0.8267, 0.8904, 0.5743],
         [0.3933, 0.3650, 0.5087, 0.2654]],

        [[0.7366, 0.7591, 0.5485, 0.4057],
         [0.0537, 0.2075, 0.1480, 0.3593],
         [0.0963, 0.4562, 0.3829, 0.2569]]])

In [ ]:
# permute
c = b.permute(2,0,1)
c

tensor([[[0.9762, 0.7793, 0.3933],
         [0.7366, 0.0537, 0.0963]],

        [[0.0405, 0.8267, 0.3650],
         [0.7591, 0.2075, 0.4562]],

        [[0.1854, 0.8904, 0.5087],
         [0.5485, 0.1480, 0.3829]],

        [[0.6252, 0.5743, 0.2654],
         [0.4057, 0.3593, 0.2569]]])

In [ ]:
# unsqueeze - used to add a dimension at a given place (useful as )
c = torch.rand(226,226,3)
c.unsqueeze(0).shape

torch.Size([1, 226, 226, 3])

In [ ]:
# squeeze
d = torch.rand(1,20)
d.squeeze(0).shape

torch.Size([20])

Numpy and Pytorch

In [ ]:
import numpy as np

In [ ]:
a = torch.tensor([1,2,3])

In [ ]:
b = a.numpy()
b

array([1, 2, 3])

In [ ]:
type(b)

numpy.ndarray

In [ ]:
c = np.array([1,2,3])

In [ ]:
d = torch.from_numpy(c)
type(d)

torch.Tensor